---
author: ~
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Jifty-Plugin-OpenID
no_index:
  directory:
    - inc
    - t
requires:
  Cache::FileCache: 0
  Jifty: 0
  LWPx::ParanoidAgent: 0
  Net::OpenID::Consumer: 0
version: undef
